# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Install k3s'
description: 'GitHub Action composite to install k3s'

inputs:
  version:
    description: 'k3s version. (e.g, v1.32.2+k3s1)'
    required: true
    default: 'v1.32.2+k3s1'

runs:
  using: "composite"
  steps:
    -
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const os = require('os');
          const path = require('path');

          const tmpDir = fs.mkdtempSync(path.join(`${{ runner.temp }}` || os.tmpdir(), 'install-k3s-'));
          const kubeconfig = `${tmpDir}/kubeconfig.yaml`;
          core.info(`Storing kubeconfig in ${kubeconfig}`);

          await exec.exec('sh', ['-c', 'curl -sfL https://get.k3s.io | sh -'], {
            env: Object.assign({}, process.env, {
              INSTALL_K3S_VERSION: '${{ inputs.version }}',
              INSTALL_K3S_EXEC: `--disable traefik --disable metrics-server --write-kubeconfig-mode 666 --write-kubeconfig ${kubeconfig}`,
            })
          });

          core.exportVariable('KUBECONFIG', kubeconfig);
          await exec.exec(`yq ${kubeconfig}`);
