name: pr-assign-author

on:
  workflow_call:

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      -
        name: Assigning author to PR
        uses: actions/github-script@v7
        with:
          script: |
            const dt = context.payload?.pull_request;
            if (!dt) {
              core.info('No pull request payload found, skipping.');
              return;
            }

            const { assignees, number, user: { login: author, type } } = dt;
            if (assignees.length > 0) {
              core.info('Pull request is already assigned to someone, skipping.');
              return;
            } else if (type !== 'User') {
              core.info('Not a user, skipping.');
              return;
            }

            const result = await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: number,
              assignees: [author]
            });

            core.debug(JSON.stringify(result, null, 2));
            core.info(`@${author} has been assigned to the pull request #${number}`);
