name: pr-assign-author

on:
  workflow_call:

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      -
        name: Assigning author to PR
        uses: actions/github-script@v7
        with:
          script: |
            const dt = context.payload?.pull_request;
            if (!dt) {
              core.warning('No pull request payload found, skipping.');
              return;
            }

            const { assignees, number, user: { login: author, type } } = dt;
            if (assignees.length > 0) {
              core.warning('Pull request is already assigned to someone, skipping.');
              return;
            } else if (type !== 'User') {
              core.warning('Not a user, skipping.');
              return;
            }

            const respCheck = await github.rest.issues.checkUserCanBeAssignedToIssue({
              ...context.repo,
              issue_number: number,
              assignee: author
            });
            core.debug(`checkUserCanBeAssignedToIssue resp: ${JSON.stringify(respCheck, null, 2)}`);
            if (respCheck.status !== 204) {
              core.warning(`Cannot assign @${author} to the pull request #${number}, skipping.`);
              return;
            }

            const respAdd = await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: number,
              assignees: [author]
            });
            core.debug(`addAssignees resp: ${JSON.stringify(respAdd, null, 2)}`);
            if (respAdd.status !== 201) {
              core.setFailed(`Failed to assign @${author} to the pull request #${number}`);
              return;
            }

            core.info(`@${author} has been assigned to the pull request #${number}`);
